### ISSUE TITLE
Joining meetings through web conf url 

### ISSUE THREAD

**Issue by 53X** [prschmid/zoomus#114]
Is there a way to join meetings from web conferencing url using this library

**Comment by tomasrojasc** [comment]
I have the same question

**Comment by periwinkleFTW** [comment]
Bumping, I have the same question

**Comment by prschmid** [comment]
Sorry for the delay in responding to everyone here! I took a very cursory look at the [Zoom REST API](https://zoom.github.io/api/), which this is wrapper for, and it doesn't seem to point to a way to do that via the REST API. If you can point to the REST endpoint for which one can use to do that, we can consider adding it as a feature in a future release. Alternatively, anyone is welcome to submit at pull request with the working code as well.
