### ISSUE TITLE
Support OAuth Authentication

### ISSUE THREAD

**Issue by jlost** [prschmid/zoomus#122]
It would be nice to support authenticating with OAuth2 bearer tokens rather than just JWT.

**Comment by jrfernandes** [comment]
You can handle the OAuth flow separately and use the generated tokens with this client:
```python
client = ZoomClient(api_key, api_secret)
client.config["token"] = oauth_generated_token
```

**Comment by pjhinton** [comment]
See also #272

**Comment by prschmid** [comment]
As Zoom only supports OAuth authentication now, as of version 1.2.0, the library has been updated accordingly.
