### ISSUE TITLE
Client is missing property for past meeting

### ISSUE THREAD

**Issue by dchess** [prschmid/zoomus#123]
https://github.com/prschmid/zoomus/blob/0fb4d5f5fd24c35ecaf4035332d0fb41c4c77068/zoomus/client.py#L26

The ZoomClient class does not have a property for calling past_meeting. A fix looks like it would require adding the following to client.py:

```python
@property
def past_meeting(self):
    """Get the past_meeting component"""
    return self.components.get("past_meeting")
```

Happy to open a PR with a fix if that would be more helpful.

**Comment by dchess** [comment]
@prschmid I opened a PR for this issue. I hope that's helpful!

**Comment by Gondee** [comment]
@dchess Thanks a lot for doing that! Hopefully mods merge it soon
