### ISSUE TITLE
Email address not being updated, no errors

### ISSUE THREAD

**Issue by HawkeyeZAR** [prschmid/zoomus#124]
I am trying to update an email address for one of our users, I can get a list of all users.
Updating the specified user does not give any errors, gives a 204 response but the email address is not changed in zoom.

`
    client = ZoomClient(KEY, SECRET)
    users = json.loads(client.user.list().content)['users']

    for user in users:
        if user['id'] == 'SOxcvf***********':
            user_data = {
                "id": user['id'],
                "email": 'test@test.com'
            }
            response = client.user.update(**user_data)
            if response.status_code == 204:
                print("Email address for %s has been updated" % user['email'])
            else:
                print("ERROR: cannot update email address. More info: {}".format(response.text))
`

**Comment by mgoette** [comment]
As far as i can see, this function doesn't support all settings. Looking into the ZOOM API documentation, the following update methods use a specific URL, like:
/users/{userId}/settings
/users/{userId}/status
/users/{userId}/password
/users/{userId}/email

The return value of the update method is missing this :
return self.patch_request("/users/{}".format(kwargs.get("id")), data=kwargs)

So either, the function has to be modified, or, maybe better, a second update function, taking the different path into consideration has to be created.

**Comment by mgoette** [comment]
By the way, theres a pull request with code which, as it seems, solves the problem:
https://github.com/prschmid/zoomus/pull/137

**Comment by HawkeyeZAR** [comment]
> By the way, theres a pull request with code which, as it seems, solves the problem:
> #137

Thanks mgoette, appreciate you looking into this.

**Comment by prschmid** [comment]
@HawkeyeZAR @mgoette Hi! We merged in #137 so hopefully this is no longer an issue. Feel free to open another issue if it still persists. Thanks!
