### ISSUE TITLE
No Documentation for Usage

### ISSUE THREAD

**Issue by rakeshgunduka** [prschmid/zoomus#149]
Dear @prschmid ,

Please add some documentation for all functions usage and parameters.
Currently in Readme it says
`client.user.create(...)`
I am sure, one can go through the source code and understand the parameters.
But for a user, it must be simple to use in my sense without going through the source code.
Frankly speaking, those three dots doesn't help at all.

Please add some documentation in Readme itself.

**Comment by prschmid** [comment]
@rakeshgunduka Thank you for your suggestion! Would you be willing to help write up some of the documentation and submit a PR? I'll happily review it. We could even have the documentation auto-generated and hosted on https://readthedocs.org/. What do you think?

**Comment by rakeshgunduka** [comment]
Sure @prschmid, I will be happy to that if it helps.

**Comment by 0xmmalik** [comment]
Has documentation been created yet?

**Comment by rakeshgunduka** [comment]
@0xmmalik I was supposed to write the documentation as requested. 
But have been busy with my work for a while. I should be able to write it soon.
@prschmid
