### ISSUE TITLE
Taking contributions?

### ISSUE THREAD

**Issue by dchess** [prschmid/zoomus#164]
@prschmid Are you accepting pull requests on this repo? I submitted #125  and #131 in August and I see no changes in the codebase since May. Anything I can do to support reviewing PRs? Looks like there are currently 25 open PRs.

**Comment by prschmid** [comment]
@dchess Apologies for the (severe) delays on my part. It's been a super busy time recently both at home and at work. I'm in the process of going through PRs (and have enlisted some help) so we should be getting through them in the near future. Thank you so much for your patience!!!!

**Comment by dchess** [comment]
@prschmid No worries! This is a very useful library (especially right now in the remote context) and I'm grateful for the work you've done to make this available. I've been using a fork in the interim, but love to be able to point directly at the main lib. 

Glad you've got some help, feel free to tap me if there's anything I can do to help.

**Comment by matthewbarr** [comment]
(If it helps, I just tested the #125 myself on a local install of 1.1.4, and can confirm it works.

**Comment by prschmid** [comment]
Merged in #125 and will be making the 1.1.5 release shortly. Thank you everyone!
