### ISSUE TITLE
generate_jwt() needs str(token, "uft-8")

### ISSUE THREAD

**Issue by erikdrums** [prschmid/zoomus#171]
Not sure why this is. I'm on python 3.7 but for token to be accepted I need to cast to string in utils.py 
```
def generate_jwt(key, secret):
    header = {"alg": "HS256", "typ": "JWT"}

    payload = {"iss": key, "exp": int(time.time() + 3600)}

    token = jwt.encode(payload, secret, algorithm="HS256", headers=header)
    return str(token, "utf-8")
```    
I found it here so it seems like it is not just me https://devforum.zoom.us/t/jwt-documentation/3881/4

**Comment by prschmid** [comment]
Hi @erikdrums . What version of the zoomus library are you using? We just put out a jwt related fix about 2 weeks ago https://github.com/prschmid/zoomus/commit/bd79bef4474db7486b36138248876dcc3741683b

**Comment by erikdrums** [comment]
Hi We are using 1.1.4

**Comment by prschmid** [comment]
Interesting. Do you happen to know if this is an issue on python 3.6 or 3.8? If you could test to see if it works / doesn't work in the other python versions, then I can try to put in a fix. Thanks for your help!

**Comment by erikdrums** [comment]
Turned out to be the PyJWT version. It was 1.7.1.
Now all is good. 
Thank for taking the time!

**Comment by prschmid** [comment]
Glad to hear that you were able to resolve it!
