### ISSUE TITLE
Support additional API hosts

### ISSUE THREAD

**Issue by gregorydlogan** [prschmid/zoomus#187]
I've built a Zoom integration for a client in the EU, which is of course subject to the GDPR.  One of their requests is that our integration use the GDPR compliant endpoint at https://eu01api-www4local.zoom.us/[1].  The current code does not appear to have a way to override the API host.  It would be nice if we could override that.

1: https://marketplace.zoom.us/docs/api-reference/introduction

**Comment by prschmid** [comment]
@gregorydlogan That's a great idea! Let me see what I can do.

**Comment by prschmid** [comment]
@gregorydlogan Working on a PR #188 for this now. Feel free to take a look at it to see if it meets your needs.

**Comment by gregorydlogan** [comment]
@prschmid I haven't had a chance to merge this into a local copy, but looks good to me!  Thanks for the quick work!
