### ISSUE TITLE
How to Delete recordings

### ISSUE THREAD

**Issue by d0d04m3** [prschmid/zoomus#208]
hi I cant found how to Delete recordings

**Comment by prschmid** [comment]
I presume the `delete` method in the [`RecordingComponent` ](https://github.com/prschmid/zoomus/blob/develop/zoomus/components/recording.py) would do the trick. 

Something like
```
client = ZoomClient('API_KEY', 'API_SECRET')
client.recording.delete(meeting_id: MY_MEETING_ID)
```

Let me know if that addresses your question.
