### ISSUE TITLE
How to list all the meetings and its info

### ISSUE THREAD

**Issue by Zaid8123** [prschmid/zoomus#209]
Can you give me a code or options to list all the meetings and their detail like Host email, Start date, Duration, Screenshare?, Recording?, License type, etc.

**Comment by prschmid** [comment]
Hello @Zaid8123 ! This library is merely a python wrapper around the [official Zoom.us API](https://marketplace.zoom.us/docs/api-reference/zoom-api). The best way to figure out how to do that would be to look at Zoom's official documentation and then find the corresponding methods in this library to make those requests.  Best of luck with your project!
