### ISSUE TITLE
When i speak..my video automatically turns to hd mode.Why? and How to fix that?

### ISSUE THREAD

**Issue by TheCoolGDev** [prschmid/zoomus#217]
I had set my video to hd mode some days ago and i have set it to normal but my video automatically turns into HD video that larger one. when i unmute and start to speak.
how to fix that?

**Comment by prschmid** [comment]
Hi @TheCoolGDev ! Sorry to hear about your troubles! This library is just a (unofficial) wrapper around the Zoom API, so not sure what is causing your issue. I would suggest looking at their documentation / contacting Zoom directly to see if you can get your problem sorted. Best of luck!
