### ISSUE TITLE
documentation example does not specify meeting ID

### ISSUE THREAD

**Issue by jaykaysharewell** [prschmid/zoomus#224]
This is taken from https://github.com/prschmid/zoomus#example-usage

client = ZoomClient('API_KEY', 'API_SECRET')
user_list_response = client.user.list()

The above cannot possibly work since no meeting is specified. There could not be any users.

**Comment by prschmid** [comment]
Thanks for using the library and suggesting a potential issue. This library is a wrapper around the Zoom API and the endpoints that are provided by them. In this particular instance, I believe the endpoint this method refers to is the following: https://marketplace.zoom.us/docs/api-reference/zoom-api/users/users

Please let us know if you find any issues going forward and feel free to submit PRs with improvements.

**Comment by Talh21** [comment]
I could not understand your answer. How do I`m choosing a specific meeting id?
