### ISSUE TITLE
migrate authentication from JWT to Server-to-Server OAuth

### ISSUE THREAD

**Issue by pjhinton** [prschmid/zoomus#272]
From the May 20, 2022, Zoom Developer platform update e-mail:

### JWT apps to be deprecated June 2023

The JWT app type will be completely deprecated as of June 2023. New and current users have 12 months to migrate their JWT based solutions to the Server-to-Server OAuth app type.

Action recommended: Create Server-to-Server OAuth app types to replace existing JWT app types. See the [Changelog](http://click.zoom.us/e/84442/des-stay-up-to-date-changelog-/c3nqff/3762653817?h=OqW0DzR47u5aDceh5N3grSQrL92cC7yNiiOlVbtLfok) for details.

### Coming Soon: Server-to-Server OAuth App Type

The Server-to-Server OAuth app type enables Developers to securely generate an Access Token without the need for user interaction. Developers can use this Access Token to enable their private server application to use scopes that account owners have granted permission to use. See the [Changelog](http://click.zoom.us/e/84442/des-stay-up-to-date-changelog-/c3nqff/3762653817?h=OqW0DzR47u5aDceh5N3grSQrL92cC7yNiiOlVbtLfok) for details.

Action recommended: In order for a Developer to access this app, admins must enable permissions for the Developer's role using [Role Management](http://click.zoom.us/e/84442/01078646-Using-role-management/c3nqft/3762653817?h=OqW0DzR47u5aDceh5N3grSQrL92cC7yNiiOlVbtLfok).

**Comment by pjhinton** [comment]
Zoom's developer documentation now has information on authenticating via server-to-server OAuth.

https://marketplace.zoom.us/docs/guides/build/server-to-server-oauth-app

**Comment by gregorydlogan** [comment]
@prschmid Are you planning on working on this?

**Comment by mfldavidson** [comment]
@gregorydlogan I no longer have maintainer access to this project but I'm planning on doing this migration for my own app that has dependency on zoomus. I can't make any promises about it being merged in but I will open a PR here once I have it done.

**Comment by prschmid** [comment]
@gregorydlogan @mfldavidson I'm terribly sorry for the lack of communication on my side! Work has been quite busy on my end and so this library has unfortunately taken a back seat. @mfldavidson If you open the PR, I'll make sure to take the time, review it, and make sure it gets merged in.

**Comment by gregorydlogan** [comment]
@mfldavidson sounds great! Any chance you've got a timeline for your work? I'm going to do some fixes on my client's integration and ideally I'd do that *after* you're done - or at least have the PR filed!

**Comment by mlhess** [comment]
I have started on this with #340 :

**Comment by woodsbw** [comment]
I have submitting this pull request, which adds S2S OAuth support without touching/breaking the current JWT implementation.

https://github.com/prschmid/zoomus/pull/341

**Comment by jjblumenfeld** [comment]
Zoom will be deprecating the JWT authentication in June and then disabling it September 1. Will this be able to be handled by then?

https://developers.zoom.us/docs/internal-apps/jwt-app-migration/

**Comment by prakash243** [comment]
Interested to know , Any news on this?

**Comment by prschmid** [comment]
Thank you everyone for your patience! The new functionality was merged in #343 and then released with version 1.2.0.

**Comment by prakash243** [comment]
Anyone tried it ?

Its not working, unable to authenticate or create a meeting.
