### ISSUE TITLE
Anyone tried it ?

### ISSUE THREAD

**Issue by prakash243** [prschmid/zoomus#350]
Anyone tried it ?

Its not working, unable to authenticate or create a meeting.

_Originally posted by @prakash243 in https://github.com/prschmid/zoomus/issues/272#issuecomment-1641528100_

**Comment by pselden** [comment]
I noticed it only supports server-to-server oauth, so not user based oauth flows.

**Comment by prakash243** [comment]
It works after adding particular scopes in app.

**Comment by prakash243** [comment]
It works after adding particular scopes in app.
