### ISSUE TITLE
Not able to transfer recording before delete the pro account.

### ISSUE THREAD

**Issue by nchidipothu** [prschmid/zoomus#40]

**Comment by nchidipothu** [comment]
Hi Team,

Can you please extend the delete method to transfer the recordsing, meeting and webnair before the user deletion.

Thanks,
Naresh Ch

**Comment by prschmid** [comment]
Hi @nchidipothu. Thank you for your feedback! Have to taken a look at the [Zoom API reference that deals with deleting users](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/userdelete)? By the looks of it, if you pass in the appropriate parameters you can do this with the current delete command. Does this address the need or are you looking for something different?

**Comment by mfldavidson** [comment]
I believe this is covered by @prschmid 's suggestion of using parameters, and since we have not heard back from @nchidipothu I am closing this. Please reopen with more info if we are incorrect!
