### ISSUE TITLE
No Content-Type setting in ApiClient.put_request

### ISSUE THREAD

**Issue by rixiaterurun** [prschmid/zoomus#92]
Hello, thank you for the nice utility for using Zoom API with Python!

https://github.com/prschmid/zoomus/blob/0fb4d5f5fd24c35ecaf4035332d0fb41c4c77068/zoomus/util.py#L185

put_request method sends json data in the request body same as post_request and patch_request, but the header does not have Content-Type field.
It causes Content-Type error, so Zoom API returns the following:
```
{"code":300,"message":"Unsupported Content Type"}
```

**Comment by seanmoreno** [comment]
Hi all. Thanks for making and supporting. This issue is still open and the PR to fix is still open. Any chance at merging this?

**Comment by mfldavidson** [comment]
Resolved by merging in #93 , closing. Thanks!
